- hosts: lbb
  gather_facts: no

  connection: ansible.netcommon.network_cli
  vars:
    #ansible_network_cli_ssh_type: libssh
    ansible_network_cli_ssh_type: paramiko

  roles:
  - { role: mwallraf.oneos_upgrader }

  post_tasks:
    - name: "DEBUG > output all variables"
      debug:
        msg: "{{ ansible_play_hosts | map('extract', hostvars) | list }}"
      run_once: yes
      delegate_to: localhost
      tags:
        - always

    - name: REPORT > save report to a file
      ansible.builtin.template:
        src: "~/.ansible/roles/mwallraf.oneos_upgrader/templates/report_overview.j2"
        dest: report.txt
        #owner: bin
        #group: wheel
      run_once: yes
      tags:
        - always

